/** @type {import('tailwindcss').Config} */
const cssVar = (name, fallback) => `var(${name}${fallback ? `, ${fallback}` : ''})`;

const appColor = (name, legacy, fallback) => cssVar(`--tw-color-${name}`, cssVar(legacy, fallback));
const appRadius = (name, legacy, fallback) => cssVar(`--tw-radius-${name}`, cssVar(legacy, fallback));
const appShadow = (name, legacy, fallback) => cssVar(`--tw-shadow-${name}`, cssVar(legacy, fallback));
const appSpace = (name, legacy, fallback) => cssVar(`--tw-space-${name}`, cssVar(legacy, fallback));
const appSize = (name, legacy, fallback) => cssVar(`--tw-size-${name}`, cssVar(legacy, fallback));
const appZ = (name, legacy, fallback) => cssVar(`--tw-z-${name}`, cssVar(legacy, fallback));

module.exports = {
  // Step 2에서는 기존 legacy class명(flex, hidden, fixed 등)과 Tailwind utility 충돌을 막기 위해
  // 모든 Tailwind utility를 tw- prefix로만 생성합니다.
  prefix: 'tw-',
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./public/index.html', './src/**/*.{vue,js}'],
  corePlugins: {
    // before_front parity를 유지하기 위해 Tailwind reset(preflight)은 사용하지 않습니다.
    // reset/root/keyboard/scrollbar는 기존 SCSS가 계속 소유합니다.
    preflight: false,
  },
  theme: {
    // Tailwind media query는 빌드 타임 값입니다.
    // 사용자 설정 breakpoint(예: 1400px)는 기존 JS/body class 로직이 계속 담당합니다.
    screens: {
      mobile: { max: '767px' },
      desktop: '768px',
      wide: '1280px',
    },
    extend: {
      colors: {
        app: {
          bg: appColor('bg', '--bg', '#ffffff'),
          chat: appColor('chat', '--chat-bg', '#ffffff'),
          mobile: appColor('mobile', '--mobile-bg', '#ffffff'),
          surface: appColor('surface', '--surface', '#ffffff'),
          surfaceStrong: appColor('surface-strong', '--surface-strong', '#ffffff'),
          surfaceMuted: appColor('surface-muted', '--surface-muted', '#f3f4f6'),
          muted: appColor('surface-muted', '--surface-muted', '#f3f4f6'),
          border: appColor('border', '--border', '#e5e7eb'),
          text: appColor('text', '--text', '#202123'),
          subtle: appColor('subtle', '--text-muted', '#6b7280'),
          placeholder: appColor('placeholder', '--placeholder', '#6b7280'),
          primary: appColor('primary', '--primary', '#10a37f'),
          primaryStrong: appColor('primary-strong', '--primary-strong', '#0e8f71'),
          primarySoft: appColor('primary-soft', '--primary-soft', 'rgba(16, 163, 127, 0.12)'),
          accent: appColor('accent', '--accent', '#5b5bd6'),
          danger: appColor('danger', '--danger', '#ef4444'),
          control: appColor('control', '--control-bg', '#ffffff'),
          controlBorder: appColor('control-border', '--control-border', '#d9d9e3'),
          controlHover: appColor('control-hover', '--control-hover', '#f3f4f6'),
          menu: appColor('menu', '--menu-bg', '#ffffff'),
          prompt: appColor('prompt', '--prompt-bg', '#ffffff'),
          promptOuter: appColor('prompt-outer', '--prompt-outer-bg', '#ffffff'),
          promptBorder: appColor('prompt-border', '--prompt-border', '#d9d9e3'),
          sidebar: appColor('sidebar', '--sidebar-bg', '#f7f7f8'),
          sidebarText: appColor('sidebar-text', '--sidebar-text', '#202123'),
          sidebarIcon: appColor('sidebar-icon', '--sidebar-icon', '#4b5563'),
          sidebarSection: appColor('sidebar-section', '--sidebar-section', '#6b7280'),
          sidebarBorder: appColor('sidebar-border', '--sidebar-border', '#e5e5e5'),
          sidebarHover: appColor('sidebar-hover', '--sidebar-hover', '#ececf1'),
          overlay: appColor('overlay', '--overlay-backdrop', 'rgba(15, 23, 42, 0.36)'),
          drawerOverlay: appColor('drawer-overlay', '--drawer-backdrop', 'rgba(0, 0, 0, 0.45)'),
          send: appColor('send', '--send-bg', '#111827'),
          sendText: appColor('send-text', '--send-text', '#ffffff'),
          code: appColor('code', '--code-bg', '#0f172a'),
          codeText: appColor('code-text', '--code-text', '#e2e8f0'),
          mobilePill: appColor('mobile-pill', '--mobile-pill-bg', '#ffffff'),
          mobilePillBorder: appColor('mobile-pill-border', '--mobile-pill-border', '#d9d9e3'),
          mobilePrompt: appColor('mobile-prompt', '--mobile-prompt-bg', '#ffffff'),
          mobileUserBubble: appColor('mobile-user-bubble', '--mobile-user-bubble', '#f4f4f4'),
          fab: appColor('fab', '--fab-bg', '#111827'),
          fabText: appColor('fab-text', '--fab-text', '#ffffff'),
          bubbleUser: appColor('bubble-user', '--bubble-user', '#f4f4f4'),
          bubbleUserText: appColor('bubble-user-text', '--bubble-user-text', '#202123'),
          bubbleAssistant: appColor('bubble-assistant', '--bubble-assistant', '#ffffff'),
          messageUser: appColor('message-user', '--message-user-bg', cssVar('--bubble-user', '#f4f4f4')),
          messageUserText: appColor('message-user-text', '--message-user-text', cssVar('--bubble-user-text', '#202123')),
          messageBorder: appColor('message-border', '--message-border', '#ececf1'),
          assistantAvatar: appColor('assistant-avatar', '--assistant-avatar-bg', '#10a37f'),
          assistantAvatarText: appColor('assistant-avatar-text', '--assistant-avatar-text', '#ffffff'),
          textOnPrimary: appColor('text-on-primary', '--text-on-primary', '#ffffff'),
          exceptionMuted: appColor('exception-muted', '--exception-muted', '#64748b'),
          exceptionButton: appColor('exception-button', '--exception-button-bg', '#111827'),
          exceptionButtonHover: appColor('exception-button-hover', '--exception-button-hover', '#1f2937'),
          exceptionButtonText: appColor('exception-button-text', '--exception-button-text', '#ffffff'),
          reasoning: appColor('reasoning', '--reasoning-bg', cssVar('--control-bg', '#ffffff')),
          reasoningBorder: appColor('reasoning-border', '--reasoning-border', cssVar('--message-border', '#ececf1')),
        },
        studio: {
          bg: appColor('studio-bg', '--studio-bg', cssVar('--bg', '#ffffff')),
          surface: appColor('studio-surface', '--studio-surface', cssVar('--surface', '#ffffff')),
          surfaceMuted: appColor('studio-surface-muted', '--studio-surface-muted', cssVar('--surface-muted', '#f7f7f8')),
          panel: appColor('studio-panel', '--studio-surface', cssVar('--surface', '#ffffff')),
          text: appColor('studio-text', '--studio-text', cssVar('--text', '#202123')),
          muted: appColor('studio-muted', '--studio-muted', cssVar('--text-muted', '#6b7280')),
          border: appColor('studio-border', '--studio-border', cssVar('--border', '#e5e7eb')),
          primary: appColor('studio-primary', '--studio-primary', cssVar('--primary', '#10a37f')),
          primaryStrong: appColor('studio-primary-strong', '--studio-primary-strong', cssVar('--primary-strong', '#0e8f71')),
          primarySoft: appColor('studio-primary-soft', '--studio-primary-soft', cssVar('--primary-soft', 'rgba(16, 163, 127, 0.12)')),
          controlHover: appColor('studio-control-hover', '--studio-control-hover', cssVar('--control-hover', '#f3f4f6')),
        },
      },
      borderRadius: {
        none: '0',
        xs: appRadius('xs', '--radius-xs', '6px'),
        sm: appRadius('sm', '--radius-sm', '10px'),
        md: appRadius('md', '--radius-md', '16px'),
        lg: appRadius('lg', '--radius-lg', '24px'),
        app: appRadius('app', '--radius-md', '16px'),
        control: appRadius('control', '--control-radius', cssVar('--radius-md', '12px')),
        controlSm: appRadius('control-sm', '--control-radius-sm', '5px'),
        prompt: appRadius('prompt', '--prompt-radius', '28px'),
        studio: appRadius('studio', '--studio-radius', '5px'),
        dialog: appRadius('dialog', '--dialog-radius', '5px'),
        dialogInput: appRadius('dialog-input', '--dialog-input-radius', '5px'),
        dialogOption: appRadius('dialog-option', '--dialog-option-radius', '5px'),
        messageUser: appRadius('message-user', '--message-user-radius', '22px'),
      },
      boxShadow: {
        app: appShadow('app', '--shadow-card', '0 8px 22px rgba(15, 23, 42, 0.06)'),
        control: appShadow('control', '--shadow-control', '0 2px 8px rgba(15, 23, 42, 0.08)'),
        menu: appShadow('menu', '--shadow-menu', '0 18px 56px rgba(15, 23, 42, 0.16)'),
        prompt: appShadow('prompt', '--shadow-prompt', '0 8px 26px rgba(15, 23, 42, 0.1)'),
        dialog: appShadow('dialog', '--dialog-panel-shadow', cssVar('--shadow-menu', '0 22px 80px rgba(15, 23, 42, 0.2)')),
      },
      fontFamily: {
        app: [cssVar('--font-family'), 'system-ui', 'sans-serif'],
        mono: [cssVar('--font-family-mono'), 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      fontSize: {
        '2xs': [cssVar('--font-size-2xs', '11px'), { lineHeight: cssVar('--line-height-body', '1.55') }],
        xs: [cssVar('--font-size-xs', '12px'), { lineHeight: cssVar('--line-height-body', '1.55') }],
        sm: [cssVar('--font-size-sm', '13px'), { lineHeight: cssVar('--line-height-body', '1.55') }],
        md: [cssVar('--font-size-md', '14px'), { lineHeight: cssVar('--line-height-body', '1.55') }],
        base: [cssVar('--font-size-base', '15px'), { lineHeight: cssVar('--line-height-body', '1.55') }],
        lg: [cssVar('--font-size-lg', '16px'), { lineHeight: cssVar('--line-height-title', '1.35') }],
        xl: [cssVar('--font-size-xl', '18px'), { lineHeight: cssVar('--line-height-title', '1.35') }],
        '2xl': [cssVar('--font-size-2xl', '22px'), { lineHeight: cssVar('--line-height-title', '1.35') }],
        '3xl': [cssVar('--font-size-3xl', '24px'), { lineHeight: cssVar('--line-height-tight', '1.25') }],
        hero: [cssVar('--font-size-hero', 'clamp(34px, 6vw, 64px)'), { lineHeight: cssVar('--line-height-tight', '1.25') }],
        fixed10: cssVar('--font-size-fixed-10', '10px'),
        fixed11: cssVar('--font-size-fixed-11', '11px'),
        fixed12: cssVar('--font-size-fixed-12', '12px'),
        fixed13: cssVar('--font-size-fixed-13', '13px'),
        fixed14: cssVar('--font-size-fixed-14', '14px'),
        fixed15: cssVar('--font-size-fixed-15', '15px'),
        fixed16: cssVar('--font-size-fixed-16', '16px'),
        fixed17: cssVar('--font-size-fixed-17', '17px'),
        fixed18: cssVar('--font-size-fixed-18', '18px'),
        fixed20: cssVar('--font-size-fixed-20', '20px'),
        fixed22: cssVar('--font-size-fixed-22', '22px'),
      },
      spacing: {
        1: appSpace('1', '--space-1', '4px'),
        2: appSpace('2', '--space-2', '8px'),
        3: appSpace('3', '--space-3', '12px'),
        4: appSpace('4', '--space-4', '16px'),
        5: appSpace('5', '--space-5', '20px'),
        6: appSpace('6', '--space-6', '24px'),
        sidebar: appSize('sidebar', '--layout-sidebar-width', '260px'),
        sidebarCollapsed: appSize('sidebar-collapsed', '--layout-sidebar-collapsed-width', '68px'),
        collapsedRail: appSize('collapsed-rail', '--layout-sidebar-collapsed-width', '68px'),
        mobileDrawer: appSize('mobile-drawer', '--layout-mobile-drawer-width', 'min(86vw, 360px)'),
        prompt: appSize('prompt', '--layout-prompt-width', '820px'),
        message: appSize('message', '--layout-message-width', '840px'),
        appHeader: appSize('app-header', '--application-header-height', '56px'),
        appFooter: appSize('app-footer', '--application-footer-height', '38px'),
        controlXs: appSize('control-xs', '--control-size-xs', '28px'),
        controlSm: appSize('control-sm', '--control-size-sm', '32px'),
        controlMd: appSize('control-md', '--control-size-md', '36px'),
        controlLg: appSize('control-lg', '--control-size-lg', '40px'),
        controlXl: appSize('control-xl', '--control-size-xl', '44px'),
        close: appSize('close', '--close-button-size', '36px'),
        mobileClose: appSize('mobile-close', '--mobile-close-button-size', '40px'),
      },
      maxWidth: {
        prompt: appSize('prompt', '--layout-prompt-width', '820px'),
        message: appSize('message', '--layout-message-width', '840px'),
        userBubbleDesktop: cssVar('--message-user-desktop-max', 'min(720px, 74%)'),
        userBubbleMobile: cssVar('--message-user-mobile-max', '88%'),
        studio: '980px',
        studioHero: '820px',
      },
      transitionDuration: {
        fast: cssVar('--duration-fast', '160ms'),
      },
      zIndex: {
        contentRaised: appZ('content-raised', '--z-content-raised', '20'),
        prompt: appZ('prompt', '--z-prompt', '70'),
        promptFloating: appZ('prompt-floating', '--z-prompt-floating', '90'),
        sidebarCollapsed: appZ('sidebar-collapsed', '--z-sidebar-collapsed', '80'),
        stickyControl: appZ('sticky-control', '--z-sticky-control', '100'),
        drawerBackdrop: appZ('drawer-backdrop', '--z-drawer-backdrop', '800'),
        drawer: appZ('drawer', '--z-drawer', '810'),
        popover: appZ('popover', '--z-popover', '900'),
        overlayBackdrop: appZ('overlay-backdrop', '--z-overlay-backdrop', '1200'),
        overlay: appZ('overlay-panel', '--z-overlay-panel', '1210'),
        modalBackdrop: appZ('modal-backdrop', '--z-modal-backdrop', '1300'),
        bottomSheetBackdrop: appZ('bottom-sheet-backdrop', '--z-bottom-sheet-backdrop', '1300'),
        bottomSheet: appZ('bottom-sheet', '--z-bottom-sheet', '1310'),
        modal: appZ('modal', '--z-modal', '1320'),
        imagePreviewBackdrop: appZ('image-preview-backdrop', '--z-image-preview-backdrop', '1500'),
        imagePreviewControl: appZ('image-preview-control', '--z-image-preview-control', '1510'),
        feedbackDialog: appZ('feedback-dialog', '--z-feedback-dialog', '1600'),
        toast: appZ('toast', '--z-toast', '3000'),
        chatHistoryMenuBackdrop: appZ('chat-history-menu-backdrop', '--z-chat-history-menu-backdrop', '2147482990'),
        virtualKeyboardPanel: appZ('virtual-keyboard-panel', '--z-virtual-keyboard-panel', '2147482999'),
        chatHistoryMenu: appZ('chat-history-menu', '--z-chat-history-menu', '2147483000'),
        virtualKeyboardFab: appZ('virtual-keyboard-fab', '--z-virtual-keyboard-fab', '2147483000'),
        appDialog: appZ('app-dialog', '--z-app-dialog', '2147482500'),
        appDialogFront: appZ('app-dialog-front', '--z-app-dialog-front', '2147483100'),
      },
    },
  },
  plugins: [
    // Do not apply global form resets in step 2.
    // Studio checkboxes/selects are still owned by legacy SCSS until the component migration step.
    require('@tailwindcss/forms')({ strategy: 'class' }),
  ],
};
