require('./freeze-css-policy.cjs');
require('./tailwind-class-integrity.cjs');
require('./bottom-sheet-structure.cjs');
require('./bootstrap-runtime.cjs');
require('./bridge-mock.cjs');
require('./mobile-state.cjs');
require('./url-policy-static.cjs');
require('./chat-flow-baseline.cjs');
require('./chat-context-static.cjs');
require('./chat-session-policy-static.cjs');
require('./chat-header-policy-static.cjs');
require('./chat-navigation-reset-static.cjs');
require('./chat-studio-portal-actions-static.cjs');
require('./chat-data-controller-static.cjs');
require('./chat-container-static.cjs');
require('./chat-public-entrypoints-static.cjs');
require('./chat-message-list-scroll-static.cjs');
require('./overlay-scroll-policy-static.cjs');
require('./overlay-scrollbar-controller-static.cjs');
require('./overlay-keyboard-controller-static.cjs');
require('./overlay-scroll-container-static.cjs');
require('./studio-create-overlay-container-static.cjs');
require('./runtime-mode-helpers-static.cjs');
require('./layout-mode-helpers-static.cjs');

console.log('all regression checks passed');
