export const BOTTOM_THRESHOLD = 48;
export const STABLE_SCROLL_DELAYS = [0, 32, 80, 160, 320, 520];
export const HISTORY_RENDER_READY_STABLE_FRAMES = 3;
export const HISTORY_RENDER_DOM_READY_MAX_FRAMES = 360;
export const HISTORY_RENDER_ANDROID_DOM_READY_MAX_FRAMES = 720;
export const HISTORY_RENDER_LAYOUT_STABLE_FRAMES = 4;
export const HISTORY_RENDER_ANDROID_LAYOUT_STABLE_FRAMES = 6;
export const HISTORY_RENDER_LAYOUT_MAX_FRAMES = 180;
export const HISTORY_RENDER_ANDROID_LAYOUT_MAX_FRAMES = 300;
export const HISTORY_RENDER_MERMAID_BATCH_SIZE = 12;
export const RESIZE_RECALCULATE_DEBOUNCE_MS = 120;
export const KEYBOARD_SUBMIT_STABLE_SCROLL_DELAYS = [
  0, 80, 160, 320, 600, 900, 1300, 1800, 2300,
];
